---
- name: Instalando o puppet no ambiente
  hosts: all
  tasks:
    - include: prerec.yml
    - include: puppet_debian.yml
      when: ansible_os_family == "Debian"
    - include: puppet_redhat.yml
      when: ansible_os_family == "RedHat"

